
CREATE TABLE facility_state_mapping (
    state VARCHAR(100),
    ideal_facility VARCHAR(10)
);

INSERT INTO facility_state_mapping VALUES
('Andaman & Nicobar Islands', 'MUM'),
('Andhra Pradesh', 'BLR'),
('Arunachal Pradesh', 'MUM'),
('Assam', 'MUM'),
('Bihar', 'HR'),
('Chandigarh', 'HR'),
('Chhattisgarh', 'MUM'),
('Dadra and Nagar Haveli and Daman and Diu', 'MUM'),
('Delhi', 'HR'),
('Goa', 'MUM'),
('Gujarat', 'MUM'),
('Haryana', 'HR'),
('Himachal Pradesh', 'HR'),
('Jammu & Kashmir', 'HR'),
('Jharkhand', 'HR'),
('Karnataka', 'BLR'),
('Kerala', 'BLR'),
('Ladakh', 'HR'),
('Lakshadweep', 'BLR'),
('Madhya Pradesh', 'MUM'),
('Maharashtra', 'MUM'),
('Manipur', 'HR'),
('Meghalaya', 'HR'),
('Mizoram', 'HR'),
('Nagaland', 'HR'),
('Odisha', 'MUM'),
('Puducherry', 'BLR'),
('Punjab', 'HR'),
('Rajasthan', 'HR'),
('Sikkim', 'HR'),
('Tamil Nadu', 'BLR'),
('Telangana', 'BLR'),
('Tripura', 'HR'),
('Uttar Pradesh', 'HR'),
('Uttarakhand', 'HR'),
('West Bengal', 'HR'),
('Daman & Diu', 'MUM');
